### ISSUE TITLE
Mycoplasma proteomes in Protein Database Downloader

### ISSUE THREAD

**Issue by Stortebecker** [galaxyproteomics/tools-galaxyp#109]
Several mycoplasma strains are very common contaminants in cell culture. Protein Database Downloader does not support mycoplasma so far. 

Could the following strains be added to Protein Database Downloader: 
- mycoplasma orale
- mycoplasma hyorhinis
- mycoplasma arginini
- mycoplasma fermentans
- mycoplasma hominis
- acheloplasma laidlawii

As those would be often downloaded together and merged afterwards, maybe it would make sense to make it possible to download all of them at once. Maybe as Taxonomy: "Common mycoplasma contaminants (M. orale, M. arginini [...])"?

**Comment by Stortebecker** [comment]
I added the mentioned species one by one to the Database Downloader (https://github.com/galaxyproteomics/tools-galaxyp/pull/110). I would still prefer a combined solution, but that should do for the moment.

**Comment by bgruening** [comment]
This is fixed by https://github.com/galaxyproteomics/tools-galaxyp/pull/110 correct?

**Comment by Stortebecker** [comment]
@bgruening I hope so.
