### ISSUE TITLE
MVP plugin for IGV

### ISSUE THREAD

**Issue by Stortebecker** [galaxyproteomics/tools-galaxyp#118]
@PratikDJagtap presented a Multi-omics visualization platform (MVP) plugin for integrated genome viewer (IGV) at the ASMS. I did not find any documentation online. How can it be integrated to Galaxy?

**Comment by PratikDJagtap** [comment]
Hello Florian,

MVP plugin for IGV is still under development. At the ASMS I must have
mentioned that this is under development at the workshop. Please contact
our Galaxy-P team in case you are interested in the plug-in for more
information.

Thanks for your interest.

Regards,
Pratik

Pratik Jagtap,

Research Assistant Professor, Department of Biochemistry, Molecular Biology
and Biophysics, University of Minnesota.

*Address: 7-166 MCB, 420 Washington Ave SE, Minneapolis, MN 55455*

*Phone: 612-624-0381 <http://612-624-0381/>    Email: pjagtap@umn.edu
<pjagtap@umn.edu>   *

*Using Galaxy for Proteomics* <http://z.umn.edu/galaxypchapter>

**Comment by Stortebecker** [comment]
Hi Pratik,

we would like to use the plugin for training. When do you plan to publish it?

Also, there are two visualization tools in https://github.com/galaxyproteomics/tools-galaxyp/tree/master/visualizations. Again, I did not find any documentation. Are they funtional and what can they be used for?

**Comment by Stortebecker** [comment]
@PratikDJagtap Ping. I am still interested in better Proteomics Visualizations. Can you pleaase brief me about your progress?

**Comment by tmcgowan** [comment]
@Stortebecker 
Hi Florian,
I plan on having a release ready in April. We've just made a large set of functionality changes. The release will include full instructions/documentation. Please let me know if you have any specific questions - mcgo002@umn.edu

-tom

**Comment by Stortebecker** [comment]
@tmcgowan Thanks Tom! April will be fine for me. Can you please ping me when it's released?
