### ISSUE TITLE
updating tools in public toolshed

### ISSUE THREAD

**Issue by jvolkening** [galaxyproteomics/tools-galaxyp#125]
I have a general question about bugfixes to tools in the public toolshed.

I'm setting up a local Galaxy instance for proteomics, and I've run into some issues with the versions of wrappers maintained by the 'galaxyp' which are in the main public toolshed. For instance, the 'myrimatch' wrapper is from 2014 and seems to  have fatal issues (backspaces inserted into the command line which cause failure). These issues have been fixed in the version in the sandbox and in this repository but don't seem to have made it back into the "stable" toolshed.

My short-term solution is to install the latest version from here (which also had some bugs but which I can submit PRs for directly). Given that the galaxy docs recommend avoiding sandboxed tools on production servers, I'm wondering if there's a system in place for fixing critical bugs to tools in the main instance even when the latest code might not be well-tested enough to put up there.

**Comment by bgruening** [comment]
@jvolkening first of all welcome to GalaxyP! Glad to see you everywhere recently! :)

A short general introduction how things should work ideally. Every tool gets tested by planemo on CI (travis in this case) if the tests fail we will not merge the PR. If they pass we can merge and the tools gets automatically pushed to the TTS (sanbox) and TS. Back at the time we don't have this testing in place and I only activated automatic TS push a few month back. To make a long story short, we need to update the TS with the latest version. I'm confident that we will not see this behavior in the future, as long as all tools are under constantly testing.

**Comment by jvolkening** [comment]
@bgruening Thanks for the explanation - I see that the updated version of myrimatch is up on TS now (see, I'm picking up the lingo). I also see that the other tools are fairly up to date - I guess I just got unlucky with the one I had trouble with.

On a somewhat related note - is there anything like Debian's ITP (intent to package) reports either with GalaxyP or Galaxy in general? I see there is a "Tool needed" label in Issues - would it make sense to have an "ITP" label?

**Comment by bgruening** [comment]
@jvolkening we are open for all kind of suggestions. So yes, this probably makes sense. I'm a little bit worried that ITP is very Debian specific and not all know that, so we decided to have something like `Tool needed` or `wishlist`. But we are open to add new labels as needed.

**Comment by jvolkening** [comment]
@bgruening Wouldn't have to be called "ITP" -- just something to say "I'm working on wrapping this tool already" to avoid duplication of effort. I see this as the flipside of the "wishlist". Just didn't know if Galaxy or GalaxyP had anything like this standardized in the ecosystem or not.
