### ISSUE TITLE
OpenMS status

### ISSUE THREAD

**Issue by jvolkening** [galaxyproteomics/tools-galaxyp#131]
Can anyone comment on the status of OpenMS in Galaxy? The TS package is owned by galaxyp but is several years old and I don't see it in the github repo. @bgruening has it in [his own tool repo](https://github.com/bgruening/galaxytools) and it looks active, but it is in the `.tt_blacklist`. Are either of these options suitable for a production server?

**Comment by bgruening** [comment]
The TTS package is based on the wrappers in https://github.com/bgruening/galaxytools and there is also the latest version. Which should work, it is for us - at least we are testing it intensively, right now.

These wrappers are auto generated and do not have tests, if we create tests, which I guess would be good, these are manual adjustments that needs to be redone after each upgrade ... so much work. I guess 2-4 tests would be great to at least tests the package and so one.

So in a summery, I have a conda package, a Docker container and the wrappers should work. I will migrate them into the GalaxyP repo as soon as our inhouse testing is done (help appreciated) - but they will be special - auto generated.

**Comment by jvolkening** [comment]
Thanks for the explanation. I'd like to install the latest version from your github repo -- is there a way to install it within the framework of the Galaxy tool manager interface, or do I need to manually copy the files in?

I agree that (1) writing tests for every single tool (and maintaining them) would be a large undertaking, and that (2) it would be good to include at least a couple of tests to check for general problems with the installation. Could this be done in a "quasi-tool" whose only function was to perform the tests and with the "hidden" attribute set? This might avoid problems during updates based on the autogeneration.

**Comment by blankclemens** [comment]
Why a quasi tool? I guess it would be reasonable to just choose one of the tools and add a test case, making sure the OpenMS installation is in general working.

Right now you would have to copy the files manually, but it is planned to move the wrappers to Galaxy-P in near future. There is an example `tool.conf` included to ease the pain.

**Comment by jvolkening** [comment]
> Why a quasi tool? I guess it would be reasonable to just choose one of the tools and add a test case, making sure the OpenMS installation is in general working.

My thinking was that if you put the tests into one of the tools, you would need to manually insert the test block into the wrapper XML each time it was re-generated from the CTD2Galaxy script. If you put it in an independent XML file it wouldn't get clobbered each time CTD2Galaxy was run but could exist side-by-side.

**Comment by blankclemens** [comment]
Good point, thanks!

**Comment by bgruening** [comment]
Updating the wrappers involved some manual invention as the generator is not perfect and I we need to at least review the diff. So I think including a test in a real tool is not much more work, but we should choose a complex tool imho, to test as many strange parameters as we can.

**Comment by bgruening** [comment]
@jvolkening can you wait until the weekend? I will try to find time to push it latest on weekend. Until then we appreciate any testing of the conda package.

**Comment by bgruening** [comment]
@jvolkening don't remember exactly, but we do not have a conda package for it, which makes everything complicated.

**Comment by jvolkening** [comment]
> Until then we appreciate any testing of the conda package.

I've been using the conda package to run various steps of the QC workflow (outside of Galaxy), with no problems so far.

**Comment by bgruening** [comment]
Awesome!

**Comment by blankclemens** [comment]
The OpenMS suite made it into the Toolshed. Feel encouraged to use and test it.
