### ISSUE TITLE
SearchGUI -prec_ppm / "Precursor Ion Tolerance Units" issue

### ISSUE THREAD

**Issue by yvanlebras** [galaxyproteomics/tools-galaxyp#135]
Dear Galaxy-P colleagues,

Testing the galaxy-p galaxy flavour, using search GUI Version 2.9.0 tools, I have changed the default "Precursor Ion Tolerance Units" to Da and have the following error: `Error parsing the prec_ppm option: Found 2 where 0 or 1 was expected.`

Cheers,

Yvan

**Comment by bgruening** [comment]
mh, ping @jj-umn

**Comment by chambm** [comment]
@yvanlebras Can you update your PeptideShaker/SearchGUI package? That bug should be fixed.
