### ISSUE TITLE
MSFragger and other Neshvizhskii Lab tools

### ISSUE THREAD

**Issue by Stortebecker** [galaxyproteomics/tools-galaxyp#149]
Referring to the [Gitter discussion](https://gitter.im/GalaxyProteomics/Lobby): Can we include this brand-new search engine: [MSFragger](http://www.nature.com/nmeth/journal/vaop/ncurrent/full/nmeth.4256.html)?

code download available here: https://secure.nouvant.com/umich/technology/7143/license/633

**Comment by Stortebecker** [comment]
The Nishvizhskii Lab seems to provide a lot of helpful proteomics software, too: http://www.nesvilab.org/software.html

Does anyone have experience with any of these? Would they be worth including?

**Comment by chambm** [comment]
Won't we need special permission because of the license? It's not a straightforward download.

**Comment by bgruening** [comment]
I guess we just need to wait until SeachGUI has support for it.
Regarding the other software I would say in general, if it's useful it's worth including. Let's decide this on a use-case level. If there is a use-case or a workflow where such a tool is needed we can put work in it.

**Comment by Stortebecker** [comment]
Still, we could ask the nesvilab for permission.

**Comment by Stortebecker** [comment]
OpenMS will provide a wrapper for MSFragger soon: https://github.com/OpenMS/OpenMS/pull/2969

**Comment by bgruening** [comment]
I wondered how they worked around the license, but then I found this:
`The MSFragger.jar can probably not be added to THIRDPARTY because of licensing.`

Nothing for us, I'm afraid. I also talked to one of the author and there is no interest in making it Open Source.
