### ISSUE TITLE
OpenMS MSGFPlusAdapter and XTandemAdapter take only one fixed modification

### ISSUE THREAD

**Issue by Stortebecker** [galaxyproteomics/tools-galaxyp#151]
The OpenMSTools MSGFPlusAdapter and XTandemAdapter allow only for one input in `param_fixed_modifications` and for `param_variable_modifications`. After adding the first one by clicking on `+ Insert param_fixed_modifications`, this option is still displayed, but nothing happens when clicking it again. The same is true for the variable modifications.

The Galaxy wrappers for MS-GF+ / XTandem allow to add more than one modification. Here, the input is solved in a different way.

**Comment by foellmelanie** [comment]
Fixed in:
https://github.com/galaxyproteomics/tools-galaxyp/pull/153
https://github.com/galaxyproteomics/tools-galaxyp/pull/154

**Comment by Stortebecker** [comment]
Thanks Meli!
