### ISSUE TITLE
MetaProSIP parameter -r_executable seems to be rendered incorrectly

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproteomics/tools-galaxyp#182]
The parameter r_executable (type="data" format="txt" value="R") renders as a selection field in Galaxy which allows to select only data sets from the history. 

This refers to revision a25d96e0d837 which should be the newest; using galaxy release 17.05. 

Is it necessary to have an R installation available? On our systems R in not available by default, but needs to be "loaded" with a command (we use http://modules.sourceforge.net/). Are there R packages needed to run the tool?

**Comment by bgruening** [comment]
@bernt-matthias does this look good to you? https://github.com/galaxyproteomics/tools-galaxyp/pull/183

**Comment by bernt-matthias** [comment]
Indeed, looks good to me. Thanks a lot.
