### ISSUE TITLE
FeatureFinderMetabo Commandline Issues

### ISSUE THREAD

**Issue by mwang87** [galaxyproteomics/tools-galaxyp#193]
It seems for FeatureFinderMetabo, the commandline arguments for mz_scoring_13C and report_convex_hulls are being written as switches instead of an optional parameter name. The input specification needs to be changed such that they are called as:

-report_convex_hulls true/false

instead of simply 

-report_convex_hulls

--Ming

**Comment by bernt-matthias** [comment]
We just finished the Galaxy tools for OpenMS 2.5. I think the problem is solved there (we give parameters now via the CTD file and not on the command line).

Feel free to reopen if necessary.
