### ISSUE TITLE
OpenMS depends on deprecated proteomics_datatypes repository

### ISSUE THREAD

**Issue by iracooke** [galaxyproteomics/tools-galaxyp#195]
Since most proteomics datatypes are now integrated into galaxy would it be possible to remove the [proteomics_datatypes](https://github.com/iracooke/proteomics-datatypes) repository as a dependency for openms? 

proteomics_datatypes contains some references to old visualisation tools that will cause startup errors like the one referenced in [this issue](https://github.com/iracooke/proteomics-datatypes/issues/6#issuecomment-327140801)

**Comment by bgruening** [comment]
Done. Thanks Ira!
