### ISSUE TITLE
multiple inputs for MapAlignerPoseClustering

### ISSUE THREAD

**Issue by trachtok** [galaxyproteomics/tools-galaxyp#251]
Hi,

I tried to use MapAlignerPoseClustering that you have just added into your Galaxy, but I encountered a problem. From a command line, I submit MapAlignerPoseClustering with multiple input files at once, but I am not able to do this in Galaxy. It always runs only with one input file and that is kind of pointless as it does not have any other files against which it would do comparisons and corrections. It is probably a stupid question but how do I start MapAlignerPoseClustering on Galaxy with several input files at once? Am I missing some button for adding another input files?

Thank you very much for your work!

**Comment by bgruening** [comment]
@trachtok any change you can test https://github.com/galaxyproteomics/tools-galaxyp/pull/254

**Comment by bernt-matthias** [comment]
I think this is solved. Also in the 2.5 version multiple input files are possible.
