### ISSUE TITLE
OpenMS tools use ini in user home directory

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproteomics/tools-galaxyp#265]
Some OpenMS tools use `~/.OpenMS/OpenMS.ini`. In a galaxy environment that runs jobs as real user this might have undesired side effects. 

I always have the following output: 
```
File '/home/songalax/.OpenMS/OpenMS.ini' is deprecated.
Updating missing/wrong entries in '/home/songalax/.OpenMS/OpenMS.ini' with defaults!
```

OpenMS tools seem to have two options that could help:
```
  -ini <file>        Use the given TOPP INI file
  -write_ini <file>  Writes the default configuration file
```

**Comment by bgruening** [comment]
Can you try to delete /home/songalax/.OpenMS/OpenMS.ini on your node?

**Comment by bernt-matthias** [comment]
Then the message disappears. But, empty `.ver` files are created per tool, e.g. `.OpenMS/FileInfo.ver`. If a user has an ini file in its home it is used. I could not find a good documentation on the file, but with `-write_ini` a file can be generated that contains default parameters for a tool.

**Comment by bernt-matthias** [comment]
Closed via https://github.com/galaxyproteomics/tools-galaxyp/issues/266
