### ISSUE TITLE
Idea collection for the next OpenMS regenerate/merge

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproteomics/tools-galaxyp#266]
This issue just contains some ideas that should be incorporated in the next openms release: 

- [x] more descriptive data set names for tools with multiple outputs: https://github.com/WorkflowConversion/CTDConverter/pull/44 via https://github.com/galaxyproteomics/tools-galaxyp/pull/383
- [ ] add test from openms
- [ ] add MetaProSIP improvements (mainly extra images as collection, see https://github.com/galaxyproteomics/tools-galaxyp/pull/263 and missing R dependencies https://github.com/galaxyproteomics/tools-galaxyp/issues/262)
- [ ] add -threads parameter which seems to be supported by many (if not most/all) tools
- [ ] check that ~/.OpenMS/OpenMS.ini is not used
- [ ] aggressive error checks https://github.com/galaxyproteomics/tools-galaxyp/pull/368
- [ ] how to deal with deprecated tools and changed parameters in autogenerated wrappers (see intense release notes of next release)

For point 1: Currently all data sets are names ${tool.name} on ${on_string}. This is confusing and should be  ${tool.name} on ${on_string}: ${FORMAT} -- or as @bgruening prefers a more content associated description instead of FORMAT

For point 2: Based on the tests in:  https://github.com/OpenMS/OpenMS/blob/8fa312ff8d6d5e97aa778283e9ec0d95750d6c5e/src/tests/topp/CMakeLists.txt and the data in: https://github.com/OpenMS/OpenMS/tree/develop/src/tests/topp it might be possible to auto generate test for the OpenMS suite... maybe for the next release.

For point 5: Some OpenMS tools use ~/.OpenMS/OpenMS.ini. In a galaxy environment that runs jobs as real user this might have undesired side effects. I always have the following output: File '/home/songalax/.OpenMS/OpenMS.ini' is deprecated. Updating missing/wrong entries in '/home/songalax/.OpenMS/OpenMS.ini' with defaults! OpenMS tools seem to have two options that could help:
```
  -ini <file>        Use the given TOPP INI file
  -write_ini <file>  Writes the default configuration file

```

**Comment by bernt-matthias** [comment]
Closed via https://github.com/galaxyproteomics/tools-galaxyp/issues/266

**Comment by jvolkening** [comment]
> add -threads parameter which seems to be supported by many (if not most/all) tools

I came here looking to post on this exact issue. I have started my own (currently short) list of tools which would benefit from adding `-threads`. I haven't done extensive testing but only checked those tools I'm currently using in workflows. Tools which utilize threading include:

* MSGFPlusAdapter (already patched to use `-threads`)
* CometAdapter
* FeatureFinderCentroided
* PeptideIndexer
* (probably many others)

Tools which don't seem to utilize threading include:

* IDPosteriorErrorProbability
* FidoAdapter
* FalseDiscoveryRate
* IDFilter
* IDMapper
* QCCalculator
* (probably many others)

I don't know if there is any way to make these determinations automatically for the rest of the TOPP toolset. I just ran the tools individually and checked the maximum CPU usage. Would it make sense to start a list to track the tools utilizing threading? Is there any point in submitting PRs to add threading for these, or will they just be lost when the wrappers are auto-generated next time?

**Comment by bgruening** [comment]
@jvolkening please PR them. If we update the wrappers we usually carefully check the diff between old and new to carry over the changes.

If anyone has an intern that can work on the script to autgenerate the wrappers let me know I have a few idea, how we can substantially improve the wrappers and make them more robust, but I do not have time for this.
The OpenMS community is not so keen of Galaxy, so we need to do this I guess at some point.
