### ISSUE TITLE
SearchGUI: Problems with tests

### ISSUE THREAD

**Issue by CarlosHorro** [galaxyproteomics/tools-galaxyp#269]
Hi,

I found some problems when creating tests for SearchGui, some of them also affecting currently existing tests:

- 'fixed_modifications' and 'variable_modifications' (loaded from "macros.xml") params:
- - receive incorrect values from their test params: "carbamidomethyl c" and "oxidation of m" instead of values present in current version of 'searchgui_mods.loc.sample' file ("Carbamidomethylation of C" and "Oxidation of M" respectively.
- - values from 'searchgui_mods.loc.sample' file don't seem to be properly loaded when I've tried it for testing. I always found "None" value instead when checking the value of "$protein_modification_options.fixed_modifications". I tried to change that file's location and its name to simply 'searchgui_mods.loc' but it still does not work.
  With these problems current tests should not work...
- I've tried to check the existence of specific files into the zip returned file, but "decompress=true" option does not seem to work for a compressed file with multiple files and I've also found many "in theory" (none of them did) ways to do it (with "output_collection" + "elements", with "discovered_dataset" or with "files_extra"). Do you know how (or if) can this be done, please?

**Comment by bgruening** [comment]
For tests with loc files, see this one here as an example: https://github.com/galaxyproject/tools-iuc/blob/master/tools/cutadapt/cutadapt.xml#L355

**Comment by bgruening** [comment]
> I've tried to check the existence of specific files into the zip returned file, but "decompress=true" option does not seem to work for a compressed file with multiple files and I've also found many "in theory" (none of them did) ways to do it (with "output_collection" + "elements", with "discovered_dataset" or with "files_extra"). Do you know how (or if) can this be done, please?

The Q I guess is, are we happy with passing the zip file around? If so you are right there is no mechanism I'm aware of that checks for a file inside a archive. This would need to be implemented in Galaxy as a new test-case. However, I hope that just comparing the size, with sim_size, is enough. For every zip file we also get a bunch of standalone files and if they are correct and the zip-file is a few kb/mb in size I hope this is enough to be confident that the tool works.
Keep in mind we are not testing the functional correctness here, but the Galaxy tool correctness.

Does this help at all? :(

**Comment by bernt-matthias** [comment]
Would the `decompress` attribute of `output` tags help?

**Comment by CarlosHorro** [comment]
> Would the `decompress` attribute of `output` tags help?

I mentioned in the first comment that it didn't work...  are there new developments related to it?

**Comment by CarlosHorro** [comment]
I will close this issue as far as we are properly managing the situation with current tests
