### ISSUE TITLE
Wrappers for MaxQuant

### ISSUE THREAD

**Issue by Stortebecker** [galaxyproteomics/tools-galaxyp#292]
After Thermo finally released it's linux-compatible [RawFileReader](http://planetorbitrap.com/rawfilereader), there is now also a linux-compatible version of [MaxQuant](https://www.nature.com/articles/s41592-018-0018-y?WT.ec_id=NMETH-201806&spMailingID=56775437&spUserID=MTg5MDk5NjQyMTU2S0&spJobID=1421218625&spReportId=MTQyMTIxODYyNQS2).

It would be great to have a Galaxy Wrapper for this.

**Comment by bernt-matthias** [comment]
seems to be on the way: https://github.com/galaxyproteomics/tools-galaxyp/pull/351

**Comment by bernt-matthias** [comment]
I guess this can be closed, since the wrappers have been released.
