### ISSUE TITLE
SearchGUI wrapper should have one and only one decoy database option

### ISSUE THREAD

**Issue by iracooke** [galaxyproteomics/tools-galaxyp#31]
There should be one option that controls whether all searches are done with decoy or not. Options to control decoy searches for individual search engines should be removed because they are confusing and would lead to weird mismatched scoring behaviour.

**Comment by bernt-matthias** [comment]
Solved. See https://github.com/galaxyproteomics/tools-galaxyp/pull/283#issuecomment-397654036
