### ISSUE TITLE
openms_suite not working

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproteomics/tools-galaxyp#310]
On my instance updating/reinstalling openms_suite does not install the latest tool versions. This would be really handy, because otherwise I would need to maintain the versions of all openms tools manually. 

I also could not find a file that describes the suite contents in this repo. 

Currently the suite lists old tool versions as "Missing repository dependencies" 

e.g. openms_msgfplusadapter | c70264573191= v1

and also some old tool versions as "Installed repository dependencies"
e.g.: 
- openms_msgfplusadapter | 708c31c03d4f = v4
- openms_msgfplusadapter | 2244cc0ac5cd = v6

But the latest version (v7) is not installed.

**Comment by bernt-matthias** [comment]
Could this be because I forgot to increase the tool version in my PR https://github.com/galaxyproteomics/tools-galaxyp/pull/263 (at least for some of the affected tools -- in particular msgfplus...).

mea culpa.

Maybe the planemo tooldshed publishing workflow could need a check for this .. and forgetful contributers like myself.

**Comment by bgruening** [comment]
How do you install the tools? Do you install this from scratch?

**Comment by bgruening** [comment]
just use `pip install ephemeris` https://github.com/galaxyproject/ephemeris, especially this one https://ephemeris.readthedocs.io/en/latest/commands/shed-tools.html you might also want to install latest master from github.

**Comment by bernt-matthias** [comment]
Got the latest version of ansible-galaxy-tools running. But it seems that the "dependencies" are not installed on my instance. So the state is that 2 old versions of each tool in the suite are installed. I also can install the suite, but the new versions of the tools in the suite are not installed. 

the following command is executed

```
/tmp/venv/bin/python /tmp/venv/bin/shed-tools install -y install_repository_dependencies: true?install_resolver_dependencies: true?install_tool_dependencies: true?name: suite_openms?owner: galaxyp?revisions:?- 0c22108365d1?- 84b7c9bd29da?- 9533f0246dd0?tool_panel_section_label: Proteomics - OpenMS?tool_shed_url: https://toolshed.g2.bx.psu.edu? -a APIKEY -g http://bioinf2:8080
```

Played around with the options install_repository_dependencies, install_resolver_dependencies, install_tool_dependencies, but even setting all to true does not install the latest revisions of the tools. 

the output is always something like:

```
[songalax@bioinf2 ~]$ cat /tmp/ephemeris__239ih 
Storing log file in: /tmp/ephemeris__239ih
(1/3) Installing repository suite_openms from galaxyp to section "Proteomics - OpenMS" at revision 84b7c9bd29da (TRT: 0:00:01.227092)
	repository suite_openms installed successfully (in 0:05:02.734756) at revision 84b7c9bd29da
(2/3) Installing repository suite_openms from galaxyp to section "Proteomics - OpenMS" at revision 9533f0246dd0 (TRT: 0:05:04.537881)
	Repository suite_openms is already installed.
	repository suite_openms installed successfully (in 0:03:42.406959) at revision 9533f0246dd0
(3/3) Installing repository suite_openms from galaxyp to section "Proteomics - OpenMS" at revision 0c22108365d1 (TRT: 0:08:47.520421)
	Repository suite_openms is already installed.
	repository suite_openms installed successfully (in 0:03:17.294711) at revision 0c22108365d1
Installed repositories (3): [('suite_openms', None), ('suite_openms', None), ('suite_openms', None)]
```

Any ideas. Maybe a bug of `shed-tools install`?

**Comment by bernt-matthias** [comment]
Yep. I already tried the 0.9 version of ephemeris. I will follow https://github.com/galaxyproject/ephemeris/issues/111 .. thanks
