### ISSUE TITLE
moFF execution problems

### ISSUE THREAD

**Issue by CarlosHorro** [galaxyproteomics/tools-galaxyp#341]
Hi,

I just started to try moFF Galaxy tool and I had 2 different problems with it:

- In one server I had registered "raw" as a data type, so when I tried to upload a Thermo raw file I could assign it the correct data type.
But in another server I did not have already registered this extension, and it seems that moFF tool did not registered, so I could not assign this data type to my Thermo raw file when uploading it.
Should not moFF register that extension by itself when installing it?

- On the other hand, when I executed moFF (on the first server) with a PSM report from PeptideShaker and that raw file, I got an exception:

```

Fatal error: Exit code 1 ()
Traceback (most recent call last):
  File "/home/parallels/GitHub/galaxy/database/dependencies/_conda/envs/__moff@1.2.1/bin/moff.py", line 20, in <module>
    import pymzml
  File "/home/parallels/GitHub/galaxy/database/dependencies/_conda/envs/__moff@1.2.1/lib/python2.7/site-packages/pymzml/__init__.py", line 24, in <module>
    raise RuntimeError('pymzML requires Python 3.4 or later.')
RuntimeError: pymzML requires Python 3.4 or later.

```

I am not sure about why it needs to use pymzML if I am not using here a mzML file, but, however, if the tool needs Python 3.4 or later I think it must install it when installing the Conda package, am I wrong?

Greetings,
Carlos

**Comment by bgruening** [comment]
@CarlosHorro we could need some help here: https://github.com/galaxyproteomics/tools-galaxyp/pull/338

I'm completely out of the loop for the next weeks, trying to organize GCC and such ... any help welcome!

**Comment by CarlosHorro** [comment]
Hi Bjorn, ok I will try to help with this stuff :-)
I will manage the Python 3.4 problem in the Conda recipe repo.

**Comment by bgruening** [comment]
Thanks a lot!!

**Comment by CarlosHorro** [comment]
I am quite surprised about the exception I talked about in the first post.
I was doing (for a different purpose) some local testing of all moFF v1 subversions and with all of them I had the same problem (I supposed the first subversions used a previous pymzml that did not require python 3, but all of them does). Am I missing something? Is it possible (in a way moFF v1 can use it) to install python 3 in the system without causing problems on Galaxy (my version is a bit old, 17.09)?

**Comment by CarlosHorro** [comment]
This seems not relevant anymore :-)
