### ISSUE TITLE
metaquantome viz: fixed pixels can squish the plot if the image is not square

### ISSUE THREAD

**Issue by caleb-easterly** [galaxyproteomics/tools-galaxyp#359]
The 600x600 works for square plots (the default), but leads to misshapen plots when the image is not square. @pravs3683, any ideas on how to fix this? i don't know if we can fix one dimension (width or height) and let the other vary...

**Comment by pravs3683** [comment]
Sorry! Missed this email. It should work to have one dimension (height or
width) fixed.

**Comment by pravs3683** [comment]
Have removed the height dimension from the HTML code. Sent a pull request.
The image now will have a fixed width of 600px. The height will be adjusted
based on the size of the image and keeping the aspect ratio.

**Comment by caleb-easterly** [comment]
thanks! merged
