### ISSUE TITLE
Metaquantome:expand error when running taxa

### ISSUE THREAD

**Issue by subinamehta** [galaxyproteomics/tools-galaxyp#363]
Hello,
I was testing metaquantome :expand taxonomy analysis and it failed giving this error:
ERROR:
Fatal error: Exit code 2 ()
usage: metaquantome [-h] {db,expand,filter,stat,viz} ...
metaquantome: error: unrecognized arguments: @

<img width="969" alt="Screen Shot 2019-03-27 at 3 29 55 PM" src="https://user-images.githubusercontent.com/27242621/55106443-5527ac00-50a5-11e9-888c-336ffb83047f.png">

**Comment by caleb-easterly** [comment]
this was fixed in f0993019d720746ff075ce5aaf17e3887a4d7939 and will be updated in galaxy tool version 0.99.5
