### ISSUE TITLE
errors in metaquantome viz wrapper

### ISSUE THREAD

**Issue by caleb-easterly** [galaxyproteomics/tools-galaxyp#365]
Tests 4-7 in the metaquantome viz wrapper are passing on my laptop with planemo but failing on Travis with the following error:

```
RunToolException: Error creating a job for these tool inputs - The selected case is unavailable/invalid.
```

They are all `f` or `ft` mode, rather than `t` mode, but I don't know what the error means and I don't know why it would work locally but not on Travis. @bgruening , any ideas?

The latest wrapper is [here](https://github.com/galaxyproteomics/tools-galaxyp/blob/improve_ui/tools/metaquantome/metaquantome_viz.xml)

**Comment by bgruening** [comment]
Hi @caleb-easterly!

This means that one parameter that needs to be set is not. I only can see your "from_dataset" parameters that can be null if not populated properly. So my guess is that those are not working.

I would also highly recommend to strucutre your tests with so many conditionals in such a way: https://github.com/galaxyproteomics/tools-galaxyp/blob/improve_ui/tools/cardinal/preprocessing.xml#L624

This makes it more readable :)

Thanks!

**Comment by caleb-easterly** [comment]
aha! i didn't know it meant a missing parameter, and that as the hint I needed - it was "ontology". thanks for the help!

I'll work on restructuring the test parameters, also.
