### ISSUE TITLE
uniprotxml_downloader dysfunctional

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproteomics/tools-galaxyp#384]
The uniprotxml_downloader seems dysfunctional. To me it appears that it just downloads a webpage (maybe indicating an error). 

Anything we can do about it?

A wish that I get a lot from my users is a tool to download the proteome for a list of taxa given by taxid (or name). The uniprotxml_downloader seemed perfect for this task or are there any alternatives.

**Comment by jj-umn** [comment]
Appears to be an issue of http vs https access.   I'll change the uniprotxml_downloader to use https to access uniprot.

**Comment by jj-umn** [comment]
@bernt-matthias 
I put version 2.1.0 in the toolshed that uses https.  Let me know if that fixes your problem.

**Comment by bernt-matthias** [comment]
Thanks a lot. I tested it briefly and it seems to work again. Wonderful. Thanks a lot.
