### ISSUE TITLE
SpectraST "cannot find 'rep_param_output_files' "

### ISSUE THREAD

**Issue by summerghw** [galaxyproteomics/tools-galaxyp#446]
hi, i was trying to use SpectraSTSearchAdapter on my own galaxy instance, but i got this error, it seems that the SpectraSTSearchAdapter.xml have some bug. `-output_files
  #for token in $rep_param_output_files:
    #if " " in str(token):
      "$token.param_output_files"
    #else
      $token.param_output_files
    #end if
  #end for
#end if
`  this variate $rep_param_output_files was not exsist.

**Comment by bernt-matthias** [comment]
OpenMS tools have been regenerated. Problem should be gone. Reopen if needed.
