### ISSUE TITLE
Percolator 3.1 vs 3.4

### ISSUE THREAD

**Issue by Slugger70** [galaxyproteomics/tools-galaxyp#461]
Hi there, we are having issues installing percolator 3.1 at the moment as the conda package will not install. Conda for Percolator 3.4 installs fine though. Are there any plans to update the percolator tool to 3.4?

**Comment by bgruening** [comment]
@Slugger70 no plans afaik, but please try your luck bumping the version.

**Comment by bernt-matthias** [comment]
Seems solved
