### ISSUE TITLE
msconvert sudo right

### ISSUE THREAD

**Issue by davidchristiany** [galaxyproteomics/tools-galaxyp#479]
Hi, 

I'm currently running msconvert (revision 9ec469ff191a) in a singularity container made from the docker container chambm/pwiz-skyline-i-agree-to-the-vendor-licenses linked in the tool requirements. (galaxy v20.01)
Msconvert use sudo in the produced command, so the singularity container need to have sudo right.
It work with a 'sudo singularity exec' but for security purpose I'd rather avoid to use sudo.
Is it possible or msconvert must use sudo ?

**Comment by chambm** [comment]
Msconvert uses sudo so it can run the command as the same user that the WINEPREFIX is owned by (Wine requires this, or cloning the WINEPREFIX so it IS owned by the user running the container) . See this PR for getting it to run with Singularity using the latter approach (cloning WINEPREFIX): https://github.com/ProteoWizard/container/pull/2
