### ISSUE TITLE
Deploy openms2.5

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproteomics/tools-galaxyp#489]
TS is not yet on 20.05. Therefore deployment of https://github.com/galaxyproteomics/tools-galaxyp/pull/415 did not work yet.

**Comment by bgruening** [comment]
We can check here: https://toolshed.g2.bx.psu.edu/api/version

**Comment by bernt-matthias** [comment]
Hrm. Now SiriusAdapter failed.

**Comment by bgruening** [comment]
I have a list with failed uploaded tools here:

* openms_peakpickerhires
* openms_noisefiltergaussian
* openms_transformationevaluation
* openms_externalcalibration

**Comment by bgruening** [comment]
Now it is just `openms_peakpickerhires`... not sure what is wrong here.

**Comment by bernt-matthias** [comment]
Guess this is done.
