### ISSUE TITLE
Peptide Shaker giving empty output

### ISSUE THREAD

**Issue by subinamehta** [galaxyproteomics/tools-galaxyp#491]
Hello,

I have been trying to run SGPS on my datasets, it works in some cases but fails in other cases. It fails to give an error report.

https://usegalaxy.eu/u/subina/h/imported-pxd019119inputmetaproteomics-09022020

Thanks,

Subina

**Comment by bernt-matthias** [comment]
I guess failing SGPS that is reported as successful should be fixed here https://github.com/galaxyproteomics/tools-galaxyp/pull/572
