### ISSUE TITLE
Help wanted getting test data for new openms tools

### ISSUE THREAD

**Issue by cat-bro** [galaxyproteomics/tools-galaxyp#494]
Hi @bernt-matthias, the new openms tools have tests but no test data so all of the tests are failing when we run `shed-tools test`.  Is there a repository of test files somewhere that we clone and add to our `tool_test_data_directories`?

**Comment by bernt-matthias** [comment]
Hi @cat-bro there is a script `test-data.sh` which generates all the test data. 

That's probably a temporary solution .. see also https://github.com/galaxyproject/tools-iuc/issues/2906

**Comment by bernt-matthias** [comment]
Hope this helped. Reopen if needed.
