### ISSUE TITLE
openms test-parameter

### ISSUE THREAD

**Issue by bgruening** [galaxyproteomics/tools-galaxyp#495]
@bernt-matthias I see this parameter in the generated CTD:

>         <ITEM name="test" value="true" type="bool" description="Enables the test mode (needed for internal use only)" required="false" advanced="true"/>

However, it should be __false__ no matter what in real life. The code is here and looks good:

https://github.com/galaxyproteomics/tools-galaxyp/blob/master/tools/openms/OpenSwathWorkflow.xml#L399

Any idea?

**Comment by bgruening** [comment]
Removing this parameter alltogether solves it:

**Comment by bgruening** [comment]
I also found this:

>     <section name="Debugging" title="Debugging" help="" expanded="false"/>

I don't think empty sections should be included.

**Comment by bernt-matthias** [comment]
Empty sections should disappear with https://github.com/WorkflowConversion/CTDConverter/pull/54/commits/346341a19c5b40c61adcfcd35037056698690f1b

**Comment by bernt-matthias** [comment]
Got it (I think). The test parameter is a ("true") boolean parameter in ctd (i.e. one that is not a string with restrictions "true", "false"). In the Galaxy xml  the parameter is rendered as text which is transformed via `bool(...)` which is always `true` :( 

Nasty bug with an easy fix. PR should follow soon.

**Comment by bgruening** [comment]
Would something like that help? https://github.com/galaxyproject/galaxy/blob/2777db0e46f1185e47c41049abdb61f99ac1e2e7/lib/galaxy/util/__init__.py#L939

**Comment by bernt-matthias** [comment]
Actually easier, since we know that there is only "true" / "false" (https://github.com/galaxyproteomics/tools-galaxyp/blob/1d1ee678c35bc262505fde58f50998f7d6586d66/tools/openms/fill_ctd.py#L185) .. started a PR
