### ISSUE TITLE
wine64 issues

### ISSUE THREAD

**Issue by summerghw** [galaxyproteomics/tools-galaxyp#508]
Hi, when i try to use msconvert on my local galaxy, this error apears `/home/galaxy/galaxy/database/jobs_directory/001/1903/tool_script.sh: line 9: wine64_anyuser: command not found`  could you help.

**Comment by bgruening** [comment]
@summerghw are you running Galaxy on Windows? Do you have Docker installed?

Can you use https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/galaxyp/msconvert/msconvert/3.0.19052.1 instead?

**Comment by summerghw** [comment]
I was using msconvert Convert and/or filter mass spectrometry files (Galaxy Version 3.0.19052.1). and my Galaxy was on linux(Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-55-generic x86_64)), i had not use docker installed.

**Comment by bgruening** [comment]
For these particular tools, you need to have Docker installed and Galaxy configured to make use of Docker for tools.

**Comment by summerghw** [comment]
@bgruening thanks a lot , I will try.

**Comment by summerghw** [comment]
@bgruening  Is there any tutorial about use docker to install tool for galaxy . that would be a great help

**Comment by bgruening** [comment]
You don't need Docker to install anything. You need to configure Galaxy to use Docker for tool execution.

Look at https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/config/sample/job_conf.xml.sample_advanced#L396 for an example config.

**Comment by summerghw** [comment]
@bgruening  thank you.

**Comment by bernt-matthias** [comment]
Singularity should also be possible now (as alternative to docker)

**Comment by summerghw** [comment]
@bernt-matthias thanks, Docker works fine,  just some permission problem which has been solved.
