### ISSUE TITLE
OpenMS peakpickerhires not updated in toolshed

### ISSUE THREAD

**Issue by foellmelanie** [galaxyproteomics/tools-galaxyp#509]
Hi all, 

on the EU server and in the toolshed there is only peakpickerhires in version 2.3.0. available but an updated version seems to exist in the test toolshed and on github. 

Maybe @bernt-matthias  you have an idea about the status of this tool? 

Thanks a lot,
Melanie

**Comment by bgruening** [comment]
For some reason nothing can be uploaded to this specific repository. I have ask @martenson to look at the logs when he has time.

**Comment by bernt-matthias** [comment]
Any news on this?

**Comment by bgruening** [comment]
No, nothing we can do here I guess. The TS admins need to look at the log. I can not push this one repo.

**Comment by martenson** [comment]
I think we resolved this yesterday with @bgruening

**Comment by bgruening** [comment]
Indeed, thanks!
