### ISSUE TITLE
PeakPickerHiRes: symbol lookup error

### ISSUE THREAD

**Issue by summerghw** [galaxyproteomics/tools-galaxyp#510]
Hi, when i try to use openms dependence tools such as PeakPickerHiRes, msgfplus, XTandemAdapter,...etc. This error apears `PeakPickerHiRes: symbol lookup error: /usr/local/bin/../lib/libOpenMS.so: undefined symbol: _ZN11xercesc_3_211InputSource11setEncodingEPKt`   I see my libOpenMS.so use `locate libOpenMS.so` `nm -D home/galaxy/galaxy/dependencies/_conda/envs/mulled-v1-15fe50e8469e2ae3649feb66e7dcaea89468d76848cca2d4e1e95525e98ad130/lib/libOpenMS.so | less `   there was a line U _ZN11xercesc_3_211InputSource11setEncodingEPKt in these files.  i tried delete dependencies openms and reinstall it , it did not work. could you help ,thanks

**Comment by bgruening** [comment]
@summerghw which server are you using? It seems that your conda installation of OpenMS is broken.

**Comment by summerghw** [comment]
@bgruening  I use local instance, should i delete all tools dependence on libOpenMS.so and reinstall them all ?

**Comment by bgruening** [comment]
If you are familiar with Conda you ca jump in home/galaxy/galaxy/dependencies/_conda/envs/mulled-v1-15fe50e8469e2ae3649feb66e7dcaea89468d76848cca2d4e1e95525e98ad130 and try to fix this env.

**Comment by bernt-matthias** [comment]
Hope this was helpful. Reopen the issue if needed.
