### ISSUE TITLE
thermorawfileparser successfully creates empty collections

### ISSUE THREAD

**Issue by martenson** [galaxyproteomics/tools-galaxyp#557]
We run the tool at version `(Galaxy Version 1.2.3+galaxy0)` and for some inputs, often instrumental quality control but also some common runs, the tool outputs an empty collection without yielding any error. What could be causing this? Is this expected for possibly invalid inputs?

example history: https://umsa.cerit-sc.cz/u/recebot_converter/h/manual-test

![Galaxy](https://user-images.githubusercontent.com/1814954/107519320-710c9c00-6bb0-11eb-85c8-3932cf2e6484.png)

**Comment by bernt-matthias** [comment]
@martenson Can you enable `Output metadata`? Then you will also get a txt/json file from which you can access stdout and stderr. Maybe this sheds some light.

**Comment by martenson** [comment]
I tried all option combinations. It ends the same. The screenshot is with included metadata as json, that's why there are two collections made (one is for the metadata).

**Comment by bgruening** [comment]
@martenson do you have access to the cluster? Can you have a look at the jwd? If not can you reproduce that at EU?

**Comment by bernt-matthias** [comment]
Error message is `2021-02-11 10:24:23 ERROR RAW file still being acquired - ./raws_folder/19_meox_tms_NP100.raw` whatever this means. 

I guess we should extend stdio error detection.
