### ISSUE TITLE
Run thermorawfileparser in parallel on collections

### ISSUE THREAD

**Issue by martenson** [galaxyproteomics/tools-galaxyp#558]
The current version puts all input files in a folder and invokes a single instance of the converter binary, which processes the files from the folder sequentially. This is not optimal for larger batches and could be heavily improved with parallelism.

local issue xref: https://github.com/RECETOX/galaxytools/issues/39

**Comment by bernt-matthias** [comment]
@martenson after our discussion at the RECETOX issue I also checked here. I guess the reason is that the ThermoRawFileParser also gets metadata (txt or json). So the main question seems to be if this can be dropped and metadata can be derived afterwards.
