### ISSUE TITLE
FileFilter some parameters are not optional

### ISSUE THREAD

**Issue by foellmelanie** [galaxyproteomics/tools-galaxyp#564]
Hi, 

In the OpenMS FileFilter version 2.5 and 2.6 some parameters seem to be set to optional despite they shouldn't be. 

Running the tool with default parameters gives the following error: 

Invalid string parameter value 'None' for parameter 'remove_mode' given! Valid values are: 'Unknown,MassSpectrum,MS1Spectrum,MSnSpectrum,SelectedIonMonitoring,SelectedReactionMonitoring,ConsecutiveReactionMonitoring,ConstantNeutralGain,ConstantNeutralLoss,Precursor,EnhancedMultiplyCharged,TimeDelayedFragmentation,ElectromagneticRadiation,Emission,Absorption'. Updating failed!
Invalid string parameter value 'None' for parameter 'remove_activation' given! Valid values are: 'Collision-induced dissociation,Post-source decay,Plasma desorption,Surface-induced dissociation,Blackbody infrared radiative dissociation,Electron capture dissociation,Infrared multiphoton dissociation,Sustained off-resonance irradiation,High-energy collision-induced dissociation,Low-energy collision-induced dissociation,Photodissociation,Electron transfer dissociation,Pulsed q dissociation'. Updating failed!
Invalid string parameter value 'None' for parameter 'select_mode' given! Valid values are: 'Unknown,MassSpectrum,MS1Spectrum,MSnSpectrum,SelectedIonMonitoring,SelectedReactionMonitoring,ConsecutiveReactionMonitoring,ConstantNeutralGain,ConstantNeutralLoss,Precursor,EnhancedMultiplyCharged,TimeDelayedFragmentation,ElectromagneticRadiation,Emission,Absorption'. Updating failed!
Invalid string parameter value 'None' for parameter 'select_activation' given! Valid values are: 'Collision-induced dissociation,Post-source decay,Plasma desorption,Surface-induced dissociation,Blackbody infrared radiative dissociation,Electron capture dissociation,Infrared multiphoton dissociation,Sustained off-resonance irradiation,High-energy collision-induced dissociation,Low-energy collision-induced dissociation,Photodissociation,Electron transfer dissociation,Pulsed q dissociation'. Updating failed!
Invalid string parameter value 'None' for parameter 'select_polarity' given! Valid values are: 'unknown,positive,negative'. Updating failed!

Once all these parameters are set to their default values the tool runs through. 

I assume this can be fixed in the wrapper by removing  'optional=True' for these parameters: 
"remove_mode", "remove_activation", "select_mode", "select_activation", "select_polarity"

@bernt-matthias I would appreciate if you could have a look ;)

Cheers,
Melanie

**Comment by bernt-matthias** [comment]
Will do.

**Comment by bernt-matthias** [comment]
Do you have a history to share?

**Comment by foellmelanie** [comment]
Here you go: https://usegalaxy.eu/u/melanie-foell/h/filefilter-test  Thanks for checking it!

**Comment by bernt-matthias** [comment]
Think I got it. Apparently a bug in Galaxy itself https://github.com/galaxyproject/galaxy/pull/11380. I'm afraid that this might take some time since it needs to be accepted, backported, and rolled out.

In addition I will check if the additional option `<option value="">default (nothing chosen)</option>` can be removed. But this is not critical and does not change anything.

**Comment by bernt-matthias** [comment]
The change in Galaxy is now available for 20.05 - 21.01. @bgruening is usegalaxy.eu updated regularly?

**Comment by bgruening** [comment]
Not automatically, but I just did it and deployment is running. @foellmelanie please reopen when it is not fixed.
