### ISSUE TITLE
Hackathon on conda packaging: September 27th and 28th

### ISSUE THREAD

**Issue by bgruening** [galaxyproteomics/tools-galaxyp#57]
Hi GalaxyP Community,

I would like to invite you to a hackathon on the September 27th and 28th. We will package as many dependencies as possible into conda packages.

Conda is a new packaging system that Galaxy can use and that enables travis tool testing, finally! Would be great if someone can join!

We will meet tomorrow here: 

https://hangouts.google.com/call/35zl5pahj5hkppxokhuxvszx24e 
and on gitter here:
https://gitter.im/GalaxyProteomics/Lobby

Some slides for a Conda quick-start can be found here: https://galaxy.slides.com/bgruening/conda-quick-start/live#/

A tool list that needs help can be found here: https://docs.google.com/spreadsheets/d/1C9p_XLiLyrbMoRVKS_H582TL1I5v9FKAv2dl5VAYxjw/edit#gid=0

**Comment by iracooke** [comment]
Hi Bjoern, 

Sounds very interesting. I will follow your progress but I cant spare any time next week to participate properly.  I'm moving next week to a new city

**Comment by bgruening** [comment]
@iracooke no problem! I will work on peptide-shaker I guess as example. Have fun moving!

**Comment by souravsingh** [comment]
@bgruening Is the issue still open? I would like to work on it.

**Comment by bgruening** [comment]
@souravsingh this is awesome! The hackathon is over yes, but I can help you to get started anytime.

**Comment by PratikDJagtap** [comment]
The first Galaxy-P CONDA hackathon will be held on September 27th and 28th.
 Galaxy-P and proteomics tool developers will particiapte in this hackathon to "CONDA-package" some of the prioritized proteomics tools within Galaxy. The hackathon will be an online event which will start
with an introduction to Galaxy structure and CONDA packaging by Bjoern Gruening. Details soon.

**Comment by bgruening** [comment]
ping @galaxyproteomics/developers!

**Comment by blankenberg** [comment]
Awesome! Any thoughts about cross posting to tools-iuc? This could be a great chance for anyone that missed @bgruening's first conda intro to get looped back in. Although, I wouldn't want to hijack/detract from the Proteomics priorities.

**Comment by bgruening** [comment]
@blankenberg done!

**Comment by lecorguille** [comment]
I'm in!

**Comment by bgruening** [comment]
Just a reminder our hackathon will start in 2 days :) Looking forward to see you all.

**Comment by iracooke** [comment]
Hi Bjoern 
I am helping in a SC course those days. If I have idle time I will try to wrap protk galaxy tools. Is there a link with a guide?

**Comment by bgruening** [comment]
@iracooke !!!
There is the official documentation: http://conda.pydata.org/docs/building/recipe.html

But I think looking at an example is in most cases enough. For example this one: https://github.com/bioconda/bioconda-recipes/tree/master/recipes/pysamstats

Install minconda2: http://conda.pydata.org/miniconda.html create those two files and run: `conda build /path/to/folder/`

**Comment by glormph** [comment]
I will be able and happy to join 28th but not 27th (EST :) ).

Do we have a packaging agenda as to which tools are prioritized?

cheers,
— 
Jorrit Boekel
Proteomics systems developer
Lehtiö lab / NBIS
Scilifelab Stockholm, Sweden

**Comment by souravsingh** [comment]
@bgruening I would like to join in the hackathon. Do we have a list of packages requiring a conda recipe?

**Comment by bgruening** [comment]
@souravsingh @glormph sounds great!
We have this one: https://docs.google.com/spreadsheets/d/1C9p_XLiLyrbMoRVKS_H582TL1I5v9FKAv2dl5VAYxjw/edit#gid=0

@PratikDJagtap need to explain this to me ;)
But essentially all tools we have here in this repo!

**Comment by PratikDJagtap** [comment]
Hello Bjoern and Conda packaging hackathon participants,

JJ has suggested that participants focus on their own tools and
applications of interest first, then help with the general list.

Ideally, the tools with priority 1 are those that would need to be tackled
first.

Thank you everyone for the participation!

Regards,
Pratik



Pratik Jagtap,
Research Assistant Professor, and
Managing Director, Center for Mass Spectrometry and Proteomics,
43 Gortner Laboratory, 1479 Gortner Avenue,
St. Paul, MN 55108
Phone: 612-624-9275
http://cbs.umn.edu/cmsp/

**Comment by chambm** [comment]
Where are the details for joining the hackathon? I.e. where do I go and at what time?

**Comment by bgruening** [comment]
@chambm I have added a link to a hangout and one to a gitter chat room. I will be there as soon as I'm awake and will give guidance. We also will have a short presentation if this is necessary!

**Comment by bgruening** [comment]
Added a link to quick-start slides at the top.

**Comment by bgruening** [comment]
Let's start the Codefest in Europe! :)

**Comment by bgruening** [comment]
If anyone needs help please ping us! We are here to help you :)

**Comment by bgruening** [comment]
This was really fun for me!!! I hope you also enjoyed it! We wrote a little summary about this hackathon and I wanted to thank you all for your amazing contributions! I think we can do this again - next time with the focus on GalaxyP tools to make use of the conda packages?

https://gist.github.com/bgruening/97b1fa16b92f5ab30b1e7c193b286432

Again, thanks a bunch for all your help!
Bjoern

**Comment by iracooke** [comment]
Fantastic work.  Sorry I was not able to participate. Hopefully next time
