### ISSUE TITLE
MaxQuant error on using .raw files

### ISSUE THREAD

**Issue by pravs3683** [galaxyproteomics/tools-galaxyp#614]
On using .raw files with maxquant on galaxy runs into an error where it is not able to find the raw file. 

I saw an issue in the config yaml file. The raw file names in the config yaml file has extra .thermo.raw appended to the file name. So if my raw file is "file1.raw" and in the experiment design I have listed as "file1", the config yaml file lists it as "file1.raw.thermo.raw"

I hope this would help in fixing the issue.

Thanks,
Praveen

**Comment by pravs3683** [comment]
@npinter Thanks for working on the MaxQuant. Would the new pull request for "fixing MaxQuant" fix this issue?

**Comment by npinter** [comment]
@pravs3683 yes this PR should fix that, we switched dependencies of the bioconda package from mono to dotnet (again). The tests failed because the updated conda package was probably not availiable.

**Comment by npinter** [comment]
@pravs3683 can you rerun your job please with https://usegalaxy.eu/tool_runner?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fgalaxyp%2Fmaxquant%2Fmaxquant%2F1.6.17.0%2Bgalaxy2 ?
The issue with Thermo RAW files should be fixed now!

**Comment by pravs3683** [comment]
Thank you! I will try it again and let you know how it goes.

Thanks again!

**Comment by pravs3683** [comment]
It didn't run successfully . It failed again with the same error message
that I encountered before.

    "for {} input files".format(len_infiles)]))
Exception: Error parsing experimental design template: Found only 0
matching entries for 4 input files


Potentially because the wrapper adds .thermo.raw to the raw files. e.g. if
my file is named "*example_raw_file.raw*" and I enter "*example_raw_file*"
in the experimental design. The config YAML file reads the raw filenames as
"*example_raw_file.raw.thermo.raw*". And this could be the reason the when
I am inputting 4 raw files, it is not able to find any, saying *0 matching
entries for 4 input files.*

**Comment by npinter** [comment]
Strange, the new version works now with Thermo RAW files in my case. File names in the YAML file consist of the original file name + the file type you select in the very beginning of the tool wrapper (in your case "thermo.raw"). Uploaded raw files then get those "new" file names. Can you provide the config.yaml as well as your experimental design here? Have you checked the experimental design section in the tool wrapper help?

```
Optional files:

        Tabular file with experimental design template:

                Currently four columns are needed: Name, Fraction, Experiment and PTM. The headers must have this exact naming. Name and Experiment are abitrary strings, Fraction is an integer or emtpy, PTM is either 'True', 'False' or empty. Consider you uploaded files named File1.mzxml, ..., File5.mzxml. This is a (syntactically) correct experimental design template:

                    Name     Fraction    Experiment   PTM
                    File1        1          E1       False
                    File2        2          E1       False
                    ghost       234        none
                    File3        3          E1       False
                    File4                   E2       True
                    File5                   E1

                This is the counter-example with one error per line:

                    Name     Fraction    Experiment   PTM
                    File1       1           E1        no  (wrong PTM value)
                    File2.mzxml 1           E2            (filename with extension)
                    File3       f3          E1            (fraction not an integer)
                    File4       1                         (missing experiment)
                                                          (File5 missing)


```

**Comment by pravs3683** [comment]
Also, can you please make sure I am using the correct version of the tool
wrapper. I am now using "MaxQuant (Galaxy Version 1.6.17.0+galaxy2)"

Here is the YAML file that is generated (The run failed but the YAML file
got generated and is accessible)

            fastaFiles:
[/data/dnb03/galaxy_db/files/5/7/0/dataset_57018956-0924-4885-99d5-9e56c1b864ef.dat]
            parseRules:
              identifierParseRule: '>.+?\|(.+?)\|'
              descriptionParseRule: '>(.+)'
            minUniquePeptides: 0
            minPepLen: 7
            maxPeptideMass: 4600
            calcPeakProperties: False
            writeMzTab: True
            separateLfq: False
            lfqStabilizeLargeRatios: True
            lfqRequireMsms: True
            advancedSiteIntensities: True
            matchBetweenRuns: False
            includeContaminants: True
            minPeptideLengthForUnspecificSearch: 8
            maxPeptideLengthForUnspecificSearch: 25
            decoyMode: revert
            peptideFdr: 0.01
            proteinFdr: 0.01
            quantMode: 1
            restrictProteinQuantification: True
            restrictMods: [Oxidation (M)]
            useCounterparts: True
            paramGroups:
              - files: ['20210615_ManishBGC_50.raw.thermo.raw',
'20210615_ManishBGC_70.raw.thermo.raw',
'20210615_ManishBGT_50.raw.thermo.raw',
'20210615_ManishBGT_70.raw.thermo.raw']
                maxMissedCleavages: 2
                fixedModifications: [Carbamidomethyl (C)]
                variableModifications: [Oxidation (M)]
                enzymes: [Trypsin/P]
                enzymeMode: 0
                lfqMode: 1
                lfqNormType: 1
                lfqMinEdgesPerNode: 3
                lfqAvEdgesPerNode: 6
                lfqMinRatioCount: 2




*And here is the experiment design:*

Name Fraction Experiment PTM
20210615_ManishBGT_70 1 Test FALSE
20210615_ManishBGT_50 2 Test FALSE
20210615_ManishBGC_70 1 Control FALSE
20210615_ManishBGC_50 2 Control FALSE


*with following input files:*

20210615_ManishBGC_50.raw
20210615_ManishBGC_70.raw
20210615_ManishBGT_50.raw
20210615_ManishBGT_70.raw




*And complete error message:*

Traceback (most recent call last):
  File "/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/galaxyp/maxquant/e42225f8a659/maxquant/create_mqpar.py",
line 48, in <module>
    mqparam = MQParam(args.template, args.exp_design, **kwargs)
  File "/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/galaxyp/maxquant/e42225f8a659/maxquant/mqparam.py",
line 121, in __init__
    self._from_yaml(yaml)
  File "/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/galaxyp/maxquant/e42225f8a659/maxquant/mqparam.py",
line 340, in _from_yaml
    self.add_infiles([pg.pop('files') for pg in paramGroups])
  File "/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/galaxyp/maxquant/e42225f8a659/maxquant/mqparam.py",
line 227, in add_infiles
    design = self._make_exp_design(groups, files)
  File "/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/galaxyp/maxquant/e42225f8a659/maxquant/mqparam.py",
line 207, in _make_exp_design
    MQParam._check_validity(design, len(files))
  File "/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/galaxyp/maxquant/e42225f8a659/maxquant/mqparam.py",
line 142, in _check_validity
    "for {} input files".format(len_infiles)]))
Exception: Error parsing experimental design template: Found only 0
matching entries for 4 input files







Thanks,
Praveen

**Comment by npinter** [comment]
@KlemensFroehlich noticed/pointed out that you have to use .raw as a "Name" in your experiment design, this might be the problem here as well.. can you try that?

New help text..
```
However, “.raw” is considered a part of the filename. Therefore, 
   Name         Fraction    Experiment   PTM
   File1.raw        1          E1       False
   File2.raw        2          E1       False
   File3.raw        3          E1       False
   File4.raw        4          E2       False
would be more appropriate as a template. Please pay special attention to your experimental design, since MaxQuant will summarize peptide and protein intensities differently depending on this input.
```

**Comment by bernt-matthias** [comment]
Assuming that this worked. Reopen if needed.
