### ISSUE TITLE
MaxQuant "StartIndex cannot be less than zero" during `Assemble_run_info` for FAIMS mzXML

### ISSUE THREAD

**Issue by eschen42** [galaxyproteomics/tools-galaxyp#639]
We have FAIMS data converted to mzXML with [FAIMS-MzXML-Generator](https://github.com/PNNL-Comp-Mass-Spec/FAIMS-MzXML-Generator).

When we attempt to run the `maxquant_mqpar` tool `Assemble_run_info` dies with "StartIndex cannot be less than zero" in `Assemble_run_info ####.error.txt`.  I have attached an example `mqpar.xml` where only the paths have been changed to protect the innocent.<br />
[job_727840_mqpar.zip](https://github.com/galaxyproteomics/tools-galaxyp/files/7419686/job_727840_mqpar.zip)

Any suggestions for how to proceed?

attn: @npinter

**Comment by eschen42** [comment]
@npinter I found that the format of mzXML needs to be MaxQuant compatible. It turns out that FAIMS-MzXML-Generator does not wrote a valid `indexOffset` node.  I was able to overcome this by running `openms_fileconverter` (which has a maxquant-compatible output mode) after FAIMS-MzXML-Generator; perhaps this could also be achieved using `msconvert` although I have not proven that to be the case, although its output could be opened by https://github.com/JurgenCox/compbio-base/tree/c6887a64b4563091feef554b18922567275e29d9/PluginRawMzXml

Thus, I am closing this issue.

**Comment by npinter** [comment]
Can you provide the `Assemble_run_info ####.error.txt` ? Looks more like an MQ issue than a Galaxy wrapper issue. 

Experiment names with a leading point maybe?
```
..
<string>.1A</string>
<string>.1A</string>
<string>.1A</string>
<string>.1B</string>
<string>.1B</string>
<string>.1B</string>
<string>.2A</string>
<string>.2A</string>
<string>.2A</string>
<string>.2B</string>
<string>.2B</string>
<string>.2B</string>
..
```
