### ISSUE TITLE
'mzxml' and 'mzml' filetypes must be lower case for workflow editor

### ISSUE THREAD

**Issue by eschen42** [galaxyproteomics/tools-galaxyp#642]
'mzxml' and 'mzml' filetypes must be specified in lower case for inputs to function properly in the workflow editor; I got orange input nodes rather than green when I tried to link an mzxml output to the inputs of maxquant or maxquant_mqpar.

To circumvent this issue, I had to hack the tool xml files in a local Galaxy; then the editor worked, and (luckily) I could upload the workflow to production Galaxies (e.g., UseGalaxy.eu) and they can be run successfully (they can even be edited so long as the connection made in an "offline Galaxy" is not severed). [Pull Request 641](https://github.com/galaxyproteomics/tools-galaxyp/pull/641) makes the case of the inputs correct, in my view, although it's currently failing because `planemo test` says that `test` isn't a valid command....

attn: @npinter

**Comment by bernt-matthias** [comment]
fixed https://github.com/galaxyproteomics/tools-galaxyp/pull/675
