### ISSUE TITLE
EggNog Mapper (Version of eggNOG Database argument)

### ISSUE THREAD

**Issue by EngyNasr** [galaxyproteomics/tools-galaxyp#648]
The "Version of eggNOG Database" argument in the tool supposedly has a drop down menu, which doesn't work, consequently the tool is not allowed to execute.

Any help with that.

**Comment by bgruening** [comment]
Can you try an older eggnoc version? I think I updated the version over the weekend but did not build a new database. 
New database build is running.

**Comment by bernt-matthias** [comment]
@EngyNasr is this fixed?
