### ISSUE TITLE
Please include new protein modifications in xml file

### ISSUE THREAD

**Issue by arman-kulyyassov** [galaxyproteomics/tools-galaxyp#669]
Dear Cristóbal Gallardo,

thank you very much for your offer. Unfortunately, I am not an IT specialist. Please include the following protein modifications to the list of variable modifications:

Glyceroyl-Lys (K) (composition H(4) O(3) C(3))
PhosphoGlyceroyl-Lys (K) (composition H(5) O(6) C(3) P)
Propionyl (K) (composition H(4) O C(3))
With best regards,

Arman

**Comment by gallardoalba** [comment]
Sorry for the late response @arman-kulyyassov.
