### ISSUE TITLE
sixgill  metaproteomics  database  for LC-MS/MS

### ISSUE THREAD

**Issue by jj-umn** [galaxyproteomics/tools-galaxyp#68]
https://github.com/dhmay/sixgill/wiki
Sixgill (Six-frame Genome-Inferred Libraries for LC-MS/MS) is a tool for using shotgun metagenomics sequencing reads to construct databases of 'metapeptides': short protein fragments for database search of LC-MS/MS metaproteomics data.
Tasks:
- [x] Conda recipe for six gill
- [ ] Datatype: metapeptides.tsv.gz - tab-delimited gzipped files
- [ ] Datatype:  MetaGeneAnnotator.txt - 
- [x] sixgill galaxy tools

**Comment by jj-umn** [comment]
```
### class SixgillMetapeptides(Binary):
    """Class describing a Sixgill Metapeptides bgzipped TSV peptidei database"""
    file_ext = "metapeptides.tsv.gz"

    def sniff( self, filename ):
        # Sixgill Metapeptides is compressed in the BGZF format, and must not be uncompressed in Galaxy.
        # The first line has column headers: sequence tlength tmin_qualscore tpartial_orf_length tmetagene_score tread_ids
        try:
            header = gzip.open( filename ).read(73)
            if header.startswith('sequence\tlength\tmin_qualscore\tpartial_orf_length\tmetagene_score\tread_ids'):
                return True
            return False
        except:
            return False

```

**Comment by jj-umn** [comment]
Start on tools in sixgill branch

**Comment by jj-umn** [comment]
https://github.com/bioconda/bioconda-recipes/pull/2596
https://github.com/galaxyproteomics/tools-galaxyp/tree/sixgill/tools/sixgill

**Comment by jj-umn** [comment]
sixgill tools committed.   sixgill version 0.2.4 has option to omit gzipping files, so no new datatype is currently needed.

**Comment by bgruening** [comment]
Great work! Thanks @jj-umn!
