### ISSUE TITLE
DecoyDatabase bug

### ISSUE THREAD

**Issue by neoformit** [galaxyproteomics/tools-galaxyp#708]
We received a ticket on usegalaxy.org.au reporting that the `-method reverse` param of DecoyDatabase does not work (that is, sequences are shuffled for both `reverse` and `shuffled` options).

Looking at the wrapper it seems like the error must lie in the `fill_ctd.py` script that appears to write an ini file.

**Comment by neoformit** [comment]
Also the test input DecoyDatabase_1.fasta does not exist

**Comment by bernt-matthias** [comment]
Test data for OpenMS is huge. So its at the moment generated with `test-data.sh`.

**Comment by bernt-matthias** [comment]
You could check if `fill_ctd.py` creates the correct entries in the ini file.

**Comment by bernt-matthias** [comment]
Seems that the Galaxy tool is correct, but the OpenMS docs quite confusing: https://github.com/OpenMS/OpenMS/pull/6844 .. `reverse` and `shuffle` do not act on the whole sequence, but only on each peptide separately .. if I get it right . 

Closing this. Feel free to reopen :)

**Comment by neoformit** [comment]
Thanks @bernt-matthias, will check this out and reply to our confused user.
