### ISSUE TITLE
Validate FASTA database fails on Usegalaxy.eu

### ISSUE THREAD

**Issue by subinamehta** [galaxyproteomics/tools-galaxyp#731]
Hello,

I have been trying to run the Validate FASTA Database(Galaxy Version 0.1.5) tool on usegalaxy.EU and it keeps failing all the time. Could you please check on this? When we run it on the local galaxy it works.

History: https://usegalaxy.eu/u/subina/h/vallidate-fasta-and-fasta-cli-issues

**Comment by bgruening** [comment]
Can you please try that again?
