### ISSUE TITLE
Quantitation tools for stable isotope labelling

### ISSUE THREAD

**Issue by Stortebecker** [galaxyproteomics/tools-galaxyp#82]
Hejhej,
I have a question regarding current options in GalaxyP for **protein quantitation**, especially on **stable isotope labels** (e.g. SILAC). While there are a lot of good possibilities for peptide identification and protein inference, I do not see many options for quantitation. There is **ProteinPilot** and **Scaffold**, but its both not freeware. The integration of **MaxQuant** was discontinued, as @bgruening told me. I am not sure, if **XPRESS** and **ASAPRatio** from the Trans-Proteomic-Pipeline have been integrated, but I would rather not recommend them to anybody. ([That's why.](https://www.ncbi.nlm.nih.gov/pubmed/?term=nilse+sigloch))

So the only possibilities I see come from the OpenMS project, e.g. **FeatureFinderMultiplex** and **ERPairFinder**. Did I get this correct or am I overlooking quantitation functions of other (free) tools?

**Comment by PratikDJagtap** [comment]
Hello Florian,

@getiria-onsongo from the Galaxy-P team has been looking at a few
quantitation tools (PyQuant, REPORTER, etc.) to be integrated into
Galaxy-P. It would be nice to have quantitation tools integrated into
Galaxy-P.

Regards,
Pratik

Pratik Jagtap,

Research Assistant Professor, Department of Biochemistry, Molecular Biology
and Biophysics,

University of Minnesota.

*Address: 7-166 MCB, 420 Washington Ave SE, Minneapolis, MN 55455*

*Phone: 612-624-0381 <http://612-624-0381/>    Email: pjagtap@umn.edu
<pjagtap@umn.edu>   *

*Twitter: twitter.com/pratikomics <http://twitter.com/pratikomics>
 Google Scholar: z.umn.edu/pjgs <http://z.umn.edu/pjgs> *

<http://z.umn.edu/galaxypreferences>

**Comment by glormph** [comment]
There is also dinosaur ( https://github.com/fickludd/dinosaur ), but I don’t think there is a Galaxy package for it yet.
cheers,
— 
Jorrit Boekel
Proteomics systems developer
Lehtiö lab / NBIS
Scilifelab Stockholm, Sweden

**Comment by jhervey4** [comment]
What instrument vendor are you acquiring data on??  

Sipros & ProRata are good combination for ID & quantification: http://sipros.omicsbio.org/
Publication: https://www.ncbi.nlm.nih.gov/pubmed/23793753

ProRata has a great deal of flexibility b/c you can specify elemental compositions between the search ID tool (Sipros) & the quantification configuration.  I used this software years ago for 15N labeling of microbes: http://pubs.acs.org/doi/abs/10.1021/pr801088f

As these tools are under development, I am hoping to add them to the Galaxy suite.  

Hope this helps!

**Comment by bgruening** [comment]
@jhervey4 awesome, please let us know if you need any kind of support for getting these tools into Galaxy and join us in https://gitter.im/GalaxyProteomics/Lobby

**Comment by bgruening** [comment]
@jhervey4 can you join us next Thursday and Friday for a Online Contribution fest? We could work on these tools.

**Comment by Stortebecker** [comment]
Hejhej, I started making a [list of tools](https://gist.github.com/Stortebecker/2c5ededcff33d10b85857952bbbdb711) that can handle PSM / peptide / protein quants. You are invited to help me complete it. 

Based on this list, we can discuss which tool would be the tool-of-choice? For my tutorials, I will start with OpenMS tools for now, as they are already available in Galaxy and can handle anything up to protein quantitation. There are many different quantitation tools in the OpenMS, though, and I will have to work out which one is best for which type of data. Does anyone have experience with these tools?
